version: '{build}'
shallow_clone: true
build_script:
- cmd: >-
    SET SLN=%CD%

    SET SRC=%SLN%\src

    SET PACKAGES=%SRC%\packages

    CD build

    SET "release="

    FOR /F "skip=1 delims=" %%i IN (UmbracoVersion.txt) DO IF NOT DEFINED release SET "release=%%i"

    ECHO AppVeyor Build %release% build%APPVEYOR_BUILD_NUMBER%
    
    SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    
    %SRC%\.nuget\NuGet.exe sources Add -Name MyGetUmbracoCore -Source https://www.myget.org/F/umbracocore/api/v2/ >NUL

    XCOPY "%SRC%\Umbraco.Tests\unit-test-log4net.CI.config" "%SRC%\Umbraco.Tests\unit-test-log4net.config" /Y
    
    build.bat -integration -release:%release% -comment:build%APPVEYOR_BUILD_NUMBER% -nugetfolder:%PACKAGES%
    
test:
  assemblies: src\Umbraco.Tests\bin\Debug\Umbraco.Tests.dll
artifacts:
- path: build\UmbracoCms.*
  name: UmbracoFiles
- path: build\msbuild.log
  name: BuildLog
notifications:
- provider: Slack
  auth_token:
    secure: v2csJi2V5ghR0rPdODK8GJdOGNCA+XaK84iQ9MdPOClqB+VU+40ybdKp6gPirGSH
  channel: '#build-umbraco-core'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false